on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Generate L3 Client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: python
        openapi-file: apidoc/L3/api-docs.yaml
        config-file: apidoc/L3/config.yaml

    - run: |
        cd python-client
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt
        python3 -m pip install -r test-requirements.txt
        python3 -m pip install .
        pytest
        cd -
        rm -rf python-client

    - name: Generate Payment Client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: python
        openapi-file: apidoc/payment/openapi.json
        config-file: apidoc/payment/config.yaml

    - run: |
        cd python-client
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt
        python3 -m pip install -r test-requirements.txt
        python3 -m pip install .
        pytest
        cd -
        rm -rf python-client
